version: '3.7'
services:
  web:
    container_name: chnge_web
    restart: always
    platform: linux/arm64
    image: toreanjoel/chnge:latest_web
    environment:
      - REACT_APP_CHNGE_API=${CHNGE_API}
    env_file:
      - web.env
    ports:
      - "4000:3000"
  api:
    container_name: chnge_api
    restart: always
    platform: linux/arm64
    image: toreanjoel/chnge:latest_api
    env_file:
      - api.env
    ports:
      - "5000:5000"
