version: '3.7'
services:
  app:
    container_name: chnge_api
    restart: always
    platform: linux/arm64
    image: toreanjoel/chnge:latest
    build: 
      context: ./api
      dockerfile: ./Dockerfile
    env_file:
      - app.env
    ports:
      - "3000:5000"
